apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend
  labels:
    app: bookstore-backend
spec:
  type: ClusterIP
  selector:
    app: bookstore-backend
  ports:
    - port: 80
      targetPort: 9001
      protocol: TCP