apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/thainguyencoffee/bookstore-fullstack/backend/k8s?ref=563caaa2ffc66fc873109107fe2e2cbf70e1b5a4

patches:
- path: patch-resource.yml
- path: patch-env.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: bookstore-backend-config

images:
- name: bookstore-backend
  newName: ghcr.io/thainguyencoffee/bookstore-fullstack/backend
  newTag: 563caaa2ffc66fc873109107fe2e2cbf70e1b5a4

replicas:
- count: 2
  name: bookstore-backend
