# Build
custom_build(
    ref = 'bookstore-gateway',
    command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
    deps = ['build.gradle', 'src']
)

# Deploy
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('bookstore-gateway', port_forwards=['9000'])