custom_build (
    ref = 'bookstore-backend',
    command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
    deps = ['build.gradle', 'src']
)

k8s_yaml(kustomize('k8s'))

k8s_resource('bookstore-backend', port_forwards=['9001'])