services:
  # Data services
  bookstore-postgres:
    image: "postgres:16"
    container_name: bookstore.postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  bookstore-redis:
    image: "redis:7.0"
    restart: always
    container_name: bookstore.redis
    ports:
      - 6379:6379

  # Keycloak service
  bookstore-keycloak:
    image: quay.io/keycloak/keycloak:24.0
    depends_on: [bookstore-postgres]
    container_name: bookstore.keycloak
    restart: always
    command: start-dev --import-realm --features=preview # Import configs provided at startup
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://bookstore-postgres:5432/keycloak
      KC_FEATURES: scripts
      KEYCLOAK_ADMIN: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost:6969/auth
      KC_HOSTNAME_ADMIN_URL: http://localhost:6969/auth
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HTTP_RELATIVE_PATH: /auth/
    ports:
      - 8080:8080