spring:
  mail:
    username: nguyennt11032004@gmail.com
    password: evcw uiui bulu mfmk

bookstore:
  vnPay:
    api-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: VMJ3LJZY
    secret-key: 90SLNCT497CFBIM299YG2ZRT439MIL8W
    return-url: http://localhost:9001/api/payment/vn-pay/return
    version: 2.1.0
    command: querydr
    order-type: other

# AWS S3
digitalocean:
  spaces:
    endpoint: https://bookstore-bucket.sgp1.digitaloceanspaces.com
    access-key: DO00XXYJDDAPT9EXWVF8
    secret-key: ZY2YAo3WrW+Eq28oLYVW89mDwst//QLJyqiF4TMP+Vg
    bucket-name: bookstore-bucket