server:
  port: 9001
  shutdown: graceful
  tomcat:
    threads:
      min-spare: 5
      max: 50
    keep-alive-timeout: 15s
    connection-timeout: 2s

spring:
  application:
    name: bookstore-be
  servlet:
    multipart:
      max-file-size: 10000000
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstoredb
    username: user
    password: password
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bookstore
  mail:
    username: nguyennt11032004@gmail.com
    password: evcw uiui bulu mfmk
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 15000
      mail.smtp.timeout: 15000
      mail.smtp.writetimeout: 15000

bookstore:
  edge-url: http://localhost:9000
  vnPay:
    api-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: VMJ3LJZY
    secret-key: 90SLNCT497CFBIM299YG2ZRT439MIL8W
    return-url: http://localhost:9001/api/payment/vn-pay/return
    version: 2.1.0
    command: querydr
    order-type: other

# AWS S3
digitalocean:
  spaces:
    endpoint: https://bookstore-bucket.sgp1.digitaloceanspaces.com
    access-key: DO00XXYJDDAPT9EXWVF8
    secret-key: ZY2YAo3WrW+Eq28oLYVW89mDwst//QLJyqiF4TMP+Vg
    bucket-name: bookstore-bucket

# Logging

# Actuator
info:
  system: Bookstore system

management:
  endpoints:
    web:
      exposure:
        include: health, info, env
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
