scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
realm_name: bookstore
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/${realm_name}
bookstore-port: 7084

server:
  port: ${bookstore-port}
  shutdown: graceful
  tomcat:
    threads:
      min-spare: 5
      max: 50
    keep-alive-timeout: 15s
    connection-timeout: 2s

spring:
  application:
    name: bookstore
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  profiles:
    active: datatest
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: secret
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer}
  mail:
    username: nguyennt11032004@gmail.com
    password: nyac pafu kohf pfwu
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 15000
      mail.smtp.timeout: 15000
      mail.smtp.writetimeout: 15000

bookstore:
  reverse-proxy-url: ${reverse-proxy-uri}
  vnPay:
    api-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: VMJ3LJZY
    secret-key: 90SLNCT497CFBIM299YG2ZRT439MIL8W
    return-url: http://localhost:9001/api/payment/vn-pay/return
    version: 2.1.0
    command: querydr
    order-type: other

# AWS S3
digitalocean:
  spaces:
    endpoint: https://bookstore-bucket.sgp1.digitaloceanspaces.com
    access-key: DO00XXYJDDAPT9EXWVF8
    secret-key: ZY2YAo3WrW+Eq28oLYVW89mDwst//QLJyqiF4TMP+Vg
    bucket-name: bookstore-bucket

# Logging

# Actuator
info:
  system: Bookstore system

management:
  endpoints:
    web:
      exposure:
        include: health, info, env
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
