apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-ui
  labels:
    app: bookstore-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-ui
  template:
    metadata:
      labels:
        app: bookstore-ui
    spec:
      containers:
        - name: bookstore-ui
          image: ghcr.io/thainguyencoffee/bookstore-fullstack/bookstore-ui:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9004
          env:
            - name: PORT
              value: "9004"
          resources:
            requests:
              memory: 128Mi
              cpu: "0.1"
            limits:
              memory: 512Mi
              cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-ui
  labels:
    app: bookstore-ui
spec:
  type: ClusterIP
  selector:
    app: bookstore-ui
  ports:
    - port: 80
      targetPort: 9004
      protocol: TCP