# Custom properties to ease configuration overrides
# on command-line or IDE launch configurations
reverse-proxy-port: 6969
vue-prefix: /vue-ui
vue-uri: http://localhost:9002/vue-ui
authorization-server-prefix: /auth
authorization-server-uri: http://localhost:8080/auth
bff-prefix: /bff
bff-uri: http://localhost:9000/bff

server:
  port: ${reverse-proxy-port}
  ssl:
    enabled: false

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        # Vue UI
        - id: vue-ui
          uri: ${vue-uri}
          predicates:
            - Path=${vue-prefix}/**

        # Authorization Server
        - id: authorization-server
          uri: ${authorization-server-uri}
          predicates:
            - Path=${authorization-server-prefix}/**

        # BFF
        - id: bff
          uri: ${bff-uri}
          predicates:
            - Path=${bff-prefix}/**
          filters:
            - StripPrefix=1
  application:
    name: reverse-proxy