server:
  port: 9001
  shutdown: graceful
  tomcat:
    threads:
      min-spare: 5
      max: 50
    keep-alive-timeout: 15s
    connection-timeout: 2s

spring:
  servlet:
    multipart:
      max-file-size: 10000000
  application:
    name: backend
  profiles:
    active: datatest
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstoredb
    username: user
    password: password
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bookstore
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyennt11032004@gmail.com
    password: lwox kogu lkqj bome
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 15000
          timeout: 15000
          starttls:
            enable: true

bookstore:
  cloudinary:
    cloud-name: dl0v8gbku
    api-key: 862736244281148
    api-secret: XuPt3no_rU3T5_fz_dCd5dhvOqo
  vnPay:
    api-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: VMJ3LJZY
    secret-key: 90SLNCT497CFBIM299YG2ZRT439MIL8W
    return-url: http://localhost:9001/api/orders/payment/return
    version: 2.1.0
    command: querydr
    order-type: other