fullnameOverride: bookstore-keycloak
commonAnnotations:
  app: bookstore-keycloak
image:
  tag: 23.0.6
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--import-realm"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_DB
    value: postgres
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: bookstore-postgres-keycloak-credentials
        key: username
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: bookstore-postgres-keycloak-credentials
        key: password
  - name: KC_DB_URL
    valueFrom:
      secretKeyRef:
        name: bookstore-postgres-keycloak-credentials
        key: url
  - name: KC_FEATURES
    value: preview
extraVolumeMounts:
  - name: config-volume
    mountPath: "/opt/bitnami/keycloak/data/import"
    readOnly: true
extraVolumes:
  - name: config-volume
    configMap:
      name: keycloak-config
startupProbe:
  enabled: true
resources:
  requests:
    cpu: 0.2
    memory: 756Mi
  limits:
    cpu: 2
    memory: 756Mi
service:
  type: LoadBalancer
  port: 80