bff-port: 9000
bff-prefix: /bff
reverse-proxy-uri: http://localhost:6969
resource-server-uri: http://localhost:9001
client-id: bookstore-confidential
client-secret: client-secret
authorities-json-path: $.roles
audience:

server:
  port: ${bff-port}

spring:
  application:
    name: bff
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: bff
          uri: ${resource-server-uri}
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
            - SaveSession
  # Security
  security:
    oauth2:
      client:
        provider:
          bookstore:
            issuer-uri: ${reverse-proxy-uri}/auth/realms/bookstore
        registration:
          bookstore:
            provider: bookstore
            authorization-grant-type: authorization_code
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope:
              - openid
              - profile
              - email
              - offline_access
# Spring addons oidc
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${reverse-proxy-uri}/auth/realms/bookstore
            authorities:
              - path: ${authorities-json-path}
            aud: ${audience}
        # SecurityFilterChain with oauth2Login() (sessions and CSRF protection enabled)
        client:
          client-uri: ${reverse-proxy-uri}${bff-prefix}
          security-matchers:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout/**
          permit-all:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout/connect/back-channel/bookstore
          csrf: cookie-accessible-from-js
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
        # SecurityFilterChain with oauth2ResourceServer() (sessions and CSRF protection disabled)
        resourceserver:
          permit-all:
            - /login-options