apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-be
  labels:
    app: bookstore-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-be
  template:
    metadata:
      labels:
        app: bookstore-be
    spec:
      containers:
        - name: bookstore-be
          image: bookstore-be
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: datatest
          livenessProbe:
            httpGet:
              port: 9001
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 9001
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - mountPath: /workspace/config
              name: bookstore-be-config-volume
      volumes:
        - name: bookstore-be-config-volume
          configMap:
            name: bookstore-be-config
