apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-gateway
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/actuator" {
        deny all;
        return 403;
      }