name: Acceptance stage Backend module
on:
  workflow_run:
    workflows: [".github/workflows/commit-stage-backend.yml"]
    types: [completed]
    branches: main

concurrency: acceptance

env:
  OWNER: thainguyencoffee
  REGISTRY: ghcr.io
  APP_REPO: bookstore-fullstack
  APP_NAME: backend
  VERSION: ${{ github.sha }}

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Trigger production stage deployment
        run: |
          gh workflow run .github/workflows/production-stage-deployment.yml \
            --field VERSION=${{ env.VERSION }} \
            --field REGISTRY=${{ env.REGISTRY }} \
            --field APP_REPO=${{ env.APP_REPO }} \
            --field APP_NAME=${{ env.APP_NAME }} \
            --field OWNER=${{ env.OWNER }} \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}