name: Acceptance stage bookstore edge module
on:
  workflow_run:
    workflows: ["Commit stage bookstore edge module"]
    types: [completed]
    branches: main

concurrency: acceptance

env:
  OWNER: thainguyencoffee
  REGISTRY: ghcr.io
  APP_REPO: bookstore-full-stack
  APP_NAME: bookstore-edge
  VERSION: ${{ github.sha }}

jobs:
  delivery:
    name: Delivery gateway module
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Trigger production stage deployment
        run: |
          gh workflow run "Production stage deployment" \
            --field VERSION=${{ env.VERSION }} \
            --field REGISTRY=${{ env.REGISTRY }} \
            --field APP_REPO=${{ env.APP_REPO }} \
            --field APP_NAME=${{ env.APP_NAME }} \
            --field OWNER=${{ env.OWNER }} \
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}