name: Commit stage bookstore backend resource server module
on:
  push:
    paths:
      - 'backend/resource-server/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: thainguyencoffee/bookstore-fullstack/bookstore/resource-server
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build and Tests
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up  JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, unit tests and integration tests
        run: |
          cd backend/resource-server
          chmod +x gradlew 
          ./gradlew build
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}/backend/resource-server"
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}