name: Commit stage bookstore
on: push

jobs:
  build:
    name: Build and Tests
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up  JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, unit tests and integration tests
        run: |
          cd backend
          chmod +x gradlew 
          ./gradlew clean build